.github/reviewer-lottery.yml
0.5h
풀리퀘스트에 2명 리뷰어가 자동 할당될 수 있게 스크립트를 작성했습니다.
=> 리뷰어 자동 할당 스크립트

client/.babelrc, client/.eslintrc.js, client/.gitignore, client/.prettierrc.js, client/jest.config.js, client/package-lock.json, client/package.json, client/src/components/App.test.tsx, client/src/components/App.tsx, client/src/index.html, client/src/index.tsx, client/tsconfig.json, client/webpack.common.js, client/webpack.dev.js, client/webpack.prod.js, server/.eslintrc.js, server/.gitignore, server/.prettierrc.js, server/package-lock.json, server/package.json, server/src/app.ts, server/tsconfig.json
- #2 
3.5h
- 웹팩, 바벨, TS 체킹
- 웹팩 asset 모듈
- jest
- eslint
=> 프로젝트 기본 세팅

.github/reviewer-lottery.yml, .github/workflows/jest.yml, .github/workflows/lint.yml, client/package.json, client/src/jest.test.ts, server/package.json
- #22 
1.0h
- `./client`, `./server` 프로젝트 ESLint
- NodeJS 14.x 
- `./client`, 프로젝트 Jest
- NodeJS 14.x
=> [#22] 프로젝트 ESLint, Jest Actions로 확인

client/src/lib/router.tsx, client/src/utils/typeGuard.ts, client/webpack.dev.js
- #4
13.5h
- 최대한 react-router-dom 라이브러리랑 같게 구현했습니다.
- Router 컴포넌트에서는 context에 대한 기본 값을 세팅합니다
- setCurrentPath를 통해 현재 path를 바꿀 수 있습니다.
- popstate에 대한 event를 등록해줍니다.
- Switch, Route는 항상 Router 컴포넌트 children으로 존재해야합니다.
- Route 컴포넌트
- path, component를 Props로 받습니다.(children으로 넣어도 됨)
- exact인 경우에는 path가 정확하게 일치해야합니다.
- path parameter를 사용할 수 있습니다.
- Link 컴포넌트
- to를 props로 받습니다
- a 태그를 사용하여 to에 해당하는 url을 pushState하여 url를 조작하고, setCurrentPath를 통해 path에 해당하는 컴포넌트를 렌더링할 수 있게 합니다.
- Switch 컴포넌트
- 여러 Route가 있는 경우 Switch안에 있는 Route들중에 처음으로 match되는 Route를 렌더링합니다
- useParams
- 현재 path에서 path parameter 값을 가져옵니다
- useHistory
- push 메소드가 있는 객체를 가져옵니다.
- push 메소드는 pathname을 받아 setCurrentPath를 실행시키는 함수입니다.
=> [#4] React router 컴포넌트 구현

server/src/app.ts, server/src/exceptions/invaild-token-exception.ts, server/src/exceptions/token-expired-exception.ts, server/src/middlewares/auth-middleware.ts, server/src/middlewares/error-middleware.ts, server/src/routers/api/category/index.ts, server/src/services/jwt.service.ts, server/src/types/express.d.ts, server/src/util/type-guard.ts, server/tsconfig.json
- #31
5h
- authType === 'guest' 인 경우 인증처리 없이 api 를 호출합니다.
- authType === 'user' 인 경우 토큰 인증 후 req.decoded 에 payload ({ email, name }) 를 넣어주고 api 를 호출합니다.
=> [#31] 인증 미들웨어 작성

server/src/middlewares/auth-middleware.ts
0.1h
auth-middleware.ts 파일에서 파일이름이 잘못 import 된 것 수정합니다.
=> fix: auth-middleware import 에러

client/package.json, client/src/components/login/OAuthButton.test.tsx
- #38 
1.0h
4인 페어 프로그래밍으로 OauthButton 테스트 코드를 작성했습니다.
1. props 테스트
2. event 테스트
3. logic 테스트 (state 가 사용된다면)
=> [#38] 프론트엔드 테스트 (OauthButton)

client/.babelrc, client/package-lock.json, client/package.json, client/src/models/category.ts, client/src/stores/categoryStore.ts, client/tsconfig.json
- #40
1.0h
- 팀원 페어 프로그래밍
- MobX의 Store와 Model 역할 정의
- Store: 비즈니스 로직
- Model: 도메인 로직
- Store에서 비동기 처리 관련 부분
- 데코레이터 문법 및 async/await 문법 관련 설정
- 카테고리 store 개발
=> [#40] MobX 기본 구조 설계 및 카테고리 Store 개발

client/src/api/category.ts, client/src/api/index.ts, client/src/lib/request.ts, client/src/models/category.ts, client/src/stores/categoryStore.ts, client/src/types/category.ts, client/src/utils/build-query-string.ts
- #41 
1.0h
- request 라이브러리를 통해 네트워크 요청
- category store에서 상태 업데이트
=> [#41] 프론트엔드 네트워크 라이브러리 개발

server/src/exceptions/page-overflow-exception.ts, server/src/middlewares/error-middleware.ts, server/src/routers/api/product/index.ts, server/src/services/product-service.ts
- #43 
0.5h
- 팀 페어 프로그래밍으로 진행
- 에러 클래스 선언
- 에러 미들웨어에서 상태 코드 정의
- 에러 발생되는 곳에 message 정의
- wrapAsync 사용
=> [#43] 에러 미들웨어 사용 예 작성 (상품목록 API: PageOverflow)

server/init.sql, server/src/loaders/db-loader.ts
- #70 
2.5h
> **사용 시 주의 사항**
> 중복된 내용이 있을 수 있으니 init.sql을 실행할땐 비워진 테이블에서 실행바랍니다
__회원, 주문, 리뷰 관련__
해당 데이터는 더미 데이터로 임의로 테스트 가능하게 작업을 했습니다.
__상품, 카테고리__
상품 데이터는 실제 `store.baemin.com`의 데이터를 모두 크롤링 해옵니다(전체 페이지)
카테고리는 임의의 카테고리로 분류하여 상품에 랜덤 카테고리를 부여했습니다
=> [#70] 데이터 삽입 SQL

.github/workflows/typescript-compile.yml
- #49 
0.5h
프론트엔드, 백엔드의 타입스크립트 컴파일 확인 CI를 추가했습니다.
=> [#49] 타입스크립트 컴파일 오류 확인 CI

server/src/models/product.ts, server/src/repositories/order-detail-repository.ts, server/src/repositories/review-repository.ts, server/src/services/order-detail-service.ts, server/src/services/review-service.ts
- #78 
0.5h
- Product 모델 id가 string 타입으로 선언되어 있어서 수정했습니다.
=> [#78] Product 모델 id 타입 수정

client/src/components/ProductDetail/MagnifierImage.test.tsx, client/src/components/ProductDetail/MagnifierImage.tsx, client/src/components/ProductDetail/ProductDetailImage.test.tsx, client/src/components/ProductDetail/ProductDetailImages.tsx
- #61 
3.5h
`useRef`를 사용했는데 이부분은 리랜더링을 최소화하기 위해 사용했습니다. 더 좋은 방식이 있다면 피드백 부탁드리겠습니다 ㅠㅜㅜ
https://user-images.githubusercontent.com/49791336/129913447-6e40a16e-d708-4ef7-a8de-12c0b519cfe0.mov
=> [#61] 상품 상세 페이지 이미지 보기 기능

client/src/models/product-image.ts, client/src/models/product-option.ts, client/src/models/product-select.ts, client/src/models/product.test.tsx, client/src/models/product.ts, client/src/models/review-image.ts, client/src/models/review.ts
- #85 
1.0h
Product관련된 모델을 정의했습니다.
메서드가 있는경우 `ModelAttributes`라는 클래스로 분리해서 `{}` 객체 리터럴로 생성을 할 수 있도록 했는데 이부분에서 모든 모델을 이렇게 할 지 아니면 메서드가 존재하는 모델만 이렇게 할지 이야기해볼 필요가 있을것 같아요!
=> [#85] 상품 관련 프론트엔드 모델 정의

server/package-lock.json, server/package.json, server/src/controllers/product-controller.ts, server/src/repositories/order-detail-repository.ts, server/src/repositories/product-repository.ts, server/src/repositories/review-repository.ts, server/src/services/order-detail-service.ts, server/src/services/product-service.ts, server/src/services/review-service.ts
- #86 
4h
- tsc-watch 설치 (`npm run dev`로 실행)
- 추천순, 인기순 정렬을 DB에서 `groupBy, orderBy` 등을 이용해 처리하도록 변경
- 위 변경에 따라 필요없어진 service, repository의 메소드 삭제
- 응답에 총 상품 갯수 (`totalProductCount`) 추가
- 응답에 상품 이미지 (productImages) 추가
- 테이블 `join`이 두 번(상품 이미지 + 리뷰 또는 주문상세) 이루어질 때 `groupBy(AVG(리뷰 점수), COUNT(주문 수))`를 사용하면 mysql의 기본 모드 중 하나인 `ONLY_FULL_GROUP_BY`에 의해서 `SELECT` 절에 `non-aggregate column(상품 이미지 id, url 등)`을 사용할 수 없다는 오류가 발생합니다. (`select`나 `leftJoinAndSelect`를 사용하지 않아도 실제 쿼리에는 포함되기 때문에..)
- productImages를 별도로 가져와서 합쳐주는 방법도 있겠지만 코드가 복잡해질 것 같아서 우선은 mysql의 옵션을 변경하는 것으로 생각하고 진행했습니다. 혹시 다른 좋은 방법이 있다면 알려주세요ㅠㅠ
- SQL 모드 변경하는 방법
```
mysql> SELECT @@global.sql_mode;
+-----------------------------------------------------------------------------------------------------------------------+
| @@global.sql_mode …
```
=> [#86] 상품목록 API 리팩토링

server/src/controllers/wish-controller.ts, server/src/exceptions/invalid-path-parameter-exception.ts, server/src/exceptions/unauthenticated-exception.ts, server/src/exceptions/user-notfound-exception.ts, server/src/middlewares/error-middleware.ts, server/src/models/wish.ts, server/src/routers/api/product/index.ts, server/src/services/user-service.ts, server/src/services/wish-service.ts
- #63 
1.5h
- POST, DELETE 메소드 작성
=> [#63] 찜하기 API

.github/workflows/dev-server-cd.yml, client/webpack.prod.js
- #59
0.5h
- production webpack config에 SERVER_URL 추가
- front-server-cd에 env파일 생성 스크립트 추가
=> [#59] 프론트엔드 production 시에 env 설정

.github/workflows/dev-server-cd.yml
- #103 
0.5h
- package.json이 바뀌는 경우만 체크하려고 하는 부분에서 파일 매칭이 잘못되어 수정했습니다.
- env에 property를 잘못 입력하여 수정하였습니다.
=> [#103] 백엔드 서버 CD 스크립트 버그 수정

client/src/pages/Notfound.tsx
- #110 
0.5h
- 메인으로 이동하는 부분까지 구현
- 라우터 적용 X
=> [#110] Notfound 페이지 레이아웃과 기능 구현

server/src/controllers/product-controller.ts, server/src/repositories/product-repository.ts, server/src/routers/api/product/index.ts, server/src/services/product-service.ts
- #107 
1.0h
- 잘나가요 (4개)
- 새로나온 상품 (4개)
- 할인중 (8개)
<전체 응답>
<상품 개별 내용>
=> [#107] 메인 상품 조회 API

client/src/components/App/App.tsx, client/src/components/Header/HeaderMain/HeaderMain.tsx, client/src/components/Header/NavBar/NavBar.tsx, client/src/components/ProductList/ProductItem/ProductItemImage.tsx, client/src/components/Review/ReviewHeader/ReviewHeader.tsx, client/src/pages/Account.tsx, client/src/pages/Product.tsx
- #115 
1.0h
- 각 UI 개발이 완료된 컴포넌트 병합
- 세세한 UI 수정
- 페이지별 라우터 설정
- 이미지 referrer 정책 수정
=> [#115] 컴포넌트 병합 및 UI 수정

client/src/api/product.ts, client/src/stores/productDetailStore.ts, client/src/types/product.ts
- #114
0.5h
- `fetch`를 통해 `product-detail`을 조회
- `Obserable`한 product 객체로 관리
=> [#114] ProductDetail Store 및 해당 상품 fetch API 요청

client/src/stores/productDetailStore.ts
- #121 
0.5h
- export default new ProductStore(); 로 변경
=> [#121] ProductDetailStore 내보낼때 인스턴스로 내보내기

client/src/containers/ProductDetailContainer.tsx, client/src/hooks/useCartsInProduct.ts, client/src/hooks/useDetailProduct.ts, client/src/models/product-option.ts, client/src/models/product.ts, client/src/stores/productDetailStore.ts, client/src/types/product.ts, client/src/utils/typeGuard.ts, server/src/controllers/product-controller.ts, server/src/validations/number-params.ts
- #120
1.0h
- `hooks`에서 `error` 상태를 반환하여 해당 상태를 `container`에서 분기합니다. 이런 방식으로 에러를 처리했습니다.
- 중간에 `cartInProduct` 오류가 있어 수정했습니다.
- 숫자 검증에 대한 Util을 추가했습니다.
- 백엔드 ProductDetail 관련되어 오류를 수정했습니다.
- Product, Option의 decimal 타입을 Number로 wrapping 했습니다.
=> [#120] 상품 디테일 UI API와 연동 및 오류 처리

client/src/api/index.ts, client/src/api/user.ts, client/src/components/App/App.tsx, client/src/components/Header/Header.tsx, client/src/components/Header/NavBar/NavBar.tsx, client/src/components/Login/OAuthButton.tsx, client/src/components/Logout/Logout.tsx, client/src/containers/LogoutContainer.tsx, client/src/containers/NavBarContianer.tsx, client/src/models/user.ts, client/src/pages/Logout.tsx, client/src/stores/userStore.ts, client/src/types/user.ts, server/src/controllers/auth-controller.ts, server/src/routers/auth/index.ts
- #118 
3h
- 백엔드 /auth/user 컨트롤러 (검증은 인증 미들웨어에서, 데이터만 보내주는 역할)
- userStore에서 토큰 파싱, localStorage set 및 get
- 로그인, 로그아웃 처리
=> [#118] 프론트엔드 로그인 처리, 백엔드와 연동, user 전역 상태로 관리

client/src/components/ProductDetail/ProductDetail.tsx, client/src/components/Review/Review.test.tsx, client/src/components/Review/Review.tsx, client/src/components/Review/ReviewList/ReviewList.tsx, client/src/components/Review/ReviewList/ReviewListItem/ReviewDetail/ReviewDetail.tsx, client/src/components/Review/ReviewList/ReviewListItem/ReviewListItem.tsx, client/src/containers/ReviewContainer.tsx, client/src/models/review.ts, client/src/pages/Product.tsx
- #125 
1.0h
- 상품 상세 페이지에서 후기 리스트 UI와 API 연동
=> [#125] 상품 상세 후기 리스트 API 연동 

server/src/controllers/delivery-address-controller.ts, server/src/exceptions/delivery-address-notfound-exception.ts, server/src/exceptions/not-my-delivery-address-exception.ts, server/src/middlewares/error-middleware.ts, server/src/repositories/delivery-address-repository.ts, server/src/routers/api/delivery-address/index.ts, server/src/routers/api/index.ts, server/src/services/delivery-address-service.ts, server/src/validations/delivery-address-create.ts, server/src/validations/delivery-address-modify.ts
- #113 
1.0h
- 배송지 CRUD 관리 API
=> [#113] 배송지 관리 API

client/src/components/Header/HeaderMain/CategoryMenu/CategoryLayer.tsx, client/src/components/Header/HeaderMain/HeaderMain.tsx, client/src/components/Header/HeaderMain/SearchBar/Dropdown.test.tsx, client/src/components/Header/HeaderMain/SearchBar/Dropdown.tsx, client/src/components/Header/HeaderMain/SearchBar/SearchBar.tsx, client/src/components/Header/HeaderMain/SearchBar/SearchTermList/SearchTermItem.tsx, client/src/components/Header/HeaderMain/SearchBar/SearchTermList/SearchTermList.tsx, client/src/containers/ProductListContainer.tsx, client/src/containers/SearchBarContainer.tsx, client/src/models/searchTerm.ts, client/src/stores/optionStore.ts
=> [#68] 최근 검색 드롭다운 UI 

server/src/repositories/product-repository.ts, server/src/validations/product-find-query.ts
- #68
1h
- findProducts에 where like 추가
=> [#68] products api에 where like 추가

client/src/components/Account/AccountNavList/AccountNavList.tsx, client/src/components/Account/AccountReview/AccountReview.tsx, client/src/components/Account/AccountReview/AccountReviewList/AccountReviewList.tsx, client/src/components/Account/AccountReview/AccountReviewList/AccountReviewListItem/AccountReviewListItem.tsx, client/src/components/Review/ReviewList/ReviewListItem/ReviewDetail/ReviewDetail.tsx, client/src/components/Review/ReviewList/ReviewListItem/ReviewDetail/ReviewDetailImage/ReviewDetailImage.tsx, client/src/components/Review/ReviewList/ReviewListItem/ReviewListItem.tsx, client/src/components/Review/ReviewList/ReviewListItem/ReviewSummary/ReviewSummary.tsx, client/src/containers/AccountReviewContainer.tsx, client/src/pages/Account.tsx
- #143
2.5h
- 내 상품후기 관리 페이지 UI (기능 미구현)
- 기존의 ReviewList, ReviewListItem 등을 가져와서(복붙...) 조금 수정하여 사용했습니다
- 재활용 가능한 부분은 최대한 해보았습니다.. (ReviewDetail 쪽)
=> [#143] 마이페이지 상품 후기 UI

client/src/components/Cart/CartModal/CountOption/CountOption.tsx, client/src/components/Cart/CartModal/CountOption/ProductCounter.tsx, client/src/containers/ProductDetailContainer.tsx, client/src/models/cart-in-product.ts, client/src/models/cart-item.ts, client/src/utils/typeGuard.ts
- #219 
2.0h
- 소수점 입력되는 것
- 무한대로 구매 가능
- 최대 수량 상수는 `cart-item`, `cart-in-product` 모델에 목데이터식으로 넣어두었습니다.
- 가능한 원래 작성된 로직이나 훅을 안 건드리고 수량 검증만 하게끔 수정해보았습니다. 문제될 것이 있는지 봐주시면 좋겠네요. 🙂
=> [#219] 상품 수량 관련 버그 해결

client/src/stores/cartStore.ts
- #226 
1.5h
- 기존 로직에 잘못된 부분이 있어서 수정했습니다.
=> [#226] 장바구니에 기존하는 상품 추가시 잘못된 상품의 수량이 올라가는 버그 해결

client/src/components/OrderPayment/OrderForm/OrderForm.tsx, client/src/components/OrderPayment/OrderPayment.tsx, client/src/containers/OrderPaymentContainer.tsx
=> [#223] 주문서 작성에 배송지 선택 기능 추가

client/src/components/ProductDetail/ProductDetail.tsx
=> 상품상세 이미지 중앙 정렬하기

client/src/api/order.ts, client/src/components/Account/AccountOrder/AccountOrder.tsx, client/src/components/Account/AccountOrder/AccountOrderTable/AccountOrderTableHeader.tsx, client/src/components/Account/AccountOrder/AccountOrderTable/AccountOrderTableItem.tsx, client/src/components/Account/AccountOrder/AccountOrderTable/AccountOrderTableItemDetail.tsx, client/src/components/App/App.tsx, client/src/containers/AccountOrderContainer.tsx, client/src/models/order.ts, client/src/models/orderDetail.ts, client/src/models/orderDetailProduct.ts, client/src/pages/Account.tsx, client/src/pages/OrderPayment.tsx, client/src/stores/orderStore.ts, client/src/types/order.ts, client/src/utils/formatDate.ts, server/src/repositories/order-repository.ts, server/src/services/order-service.ts
=> [#221] 마이페이지 주문 관리 탭 추가

.github/workflows/prod-server-cd.yml
- #239
0.5h
production 배포 스크립트 작성
=> [#239] production 환경 배포 스크립트

client/src/components/Account/AccountOrder/AccountOrderTable/AccountOrderTableItemDetail.tsx, client/src/components/Cart/Cart.tsx, client/src/components/Cart/CartModal/CountOption/ProductCounter.tsx, client/src/components/Cart/CartModal/OptionContainer/OptionContainer.tsx, client/src/components/Cart/CartTable/CartItem/CartItem.tsx, client/src/components/Footer/Footer.tsx, client/src/components/Header/HeaderMain/HeaderMain.tsx, client/src/components/Header/HeaderMain/SearchBar/SearchBar.tsx, client/src/components/Header/NavBar/NavBar.tsx, client/src/components/MainProductSections/MainAdList/MainAdListItem.tsx, client/src/components/MainProductSections/MainProductList.tsx, client/src/components/OrderPayment/OrderTable/OrderDetailProductItem.tsx, client/src/components/ProductDetail/ProductCart/ProductCartItem.tsx, client/src/components/ProductDetail/ProductCart/ProductCounter.tsx, client/src/components/ProductDetail/ProductImage/MagnifierImage.tsx, client/src/components/ProductDetail/ProductImage/ProductDetailImages.tsx, client/src/components/ProductDetail/ProductInfoBox.tsx, client/src/components/ProductList/ProductItem/ProductItem.tsx, client/src/components/ProductList/ProductItem/ProductItemImage.tsx, client/src/components/Review/ReviewList/ReviewListItem/ReviewDetail/ReviewDetailImage/ReviewDetailImage.tsx, client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostImages/ReviewPostImages.tsx, client/src/components/WishList/WishItem/WishItem.tsx, client/src/index.html, client/src/lib/router.tsx
=> [#246] 웹 접근성 향상

client/src/components/Account/AccountOrder/AccountOrderTable/AccountOrderTableItemDetail.tsx, client/src/components/Cart/Cart.tsx, client/src/components/Cart/CartModal/CountOption/ProductCounter.tsx, client/src/components/Cart/CartModal/OptionContainer/OptionContainer.tsx, client/src/components/Cart/CartTable/CartItem/CartItem.tsx, client/src/components/Footer/Footer.tsx, client/src/components/Header/HeaderMain/HeaderMain.tsx, client/src/components/Header/HeaderMain/SearchBar/SearchBar.tsx, client/src/components/Header/NavBar/NavBar.tsx, client/src/components/MainProductSections/MainAdList/MainAdListItem.tsx, client/src/components/MainProductSections/MainProductList.tsx, client/src/components/OrderPayment/OrderTable/OrderDetailProductItem.tsx, client/src/components/ProductDetail/ProductCart/ProductCartItem.tsx, client/src/components/ProductDetail/ProductCart/ProductCounter.tsx, client/src/components/ProductDetail/ProductImage/MagnifierImage.tsx, client/src/components/ProductDetail/ProductImage/ProductDetailImages.tsx, client/src/components/ProductDetail/ProductInfoBox.tsx, client/src/components/ProductList/ProductItem/ProductItem.tsx, client/src/components/ProductList/ProductItem/ProductItemImage.tsx, client/src/components/Review/ReviewList/ReviewListItem/ReviewDetail/ReviewDetailImage/ReviewDetailImage.tsx, client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostImages/ReviewPostImages.tsx, client/src/components/WishList/WishItem/WishItem.tsx, client/src/index.html, client/src/lib/router.tsx
Reverts woowa-techcamp-2021/store-4#254
=> Revert [#246] 웹 접근성 향상

client/src/components/MainProductSections/mock/index.ts, client/src/containers/CarouselContainer.tsx
=> [#244] 메인 AD 링크 ID 수정

client/src/containers/ProductListContainer.tsx, client/src/pages/Products.tsx
=> [#248] 상품 목록 페이지 번호

client/src/components/Account/AccountReview/AccountReview.tsx
=> [#251] 내 상품후기 제목 추가

client/src/hoc/withAuthentication.tsx, client/src/pages/Account.tsx, client/src/pages/OrderPayment.tsx, client/src/stores/userStore.ts
- #253 
0.5h
- withAuth hoc 구조 약간 변경(toast를 useEffect 안으로 넣으면서 setTimeout 제거)
- window.replaceState -> useHistory로 대체
- userStore에 불필요한 replaceState 제거
=> [#253] useHistory 사용 / 불필요한 window.history.replaceState() 제거

client/src/containers/CartContainer.tsx, client/src/containers/DeliveryAddressItemContainer.tsx, client/src/containers/ManageDeliveryAddressContainer.tsx, client/src/containers/OrderPaymentContainer.tsx, client/src/containers/ProductDetailContainer.tsx, client/src/containers/ReviewPostFormContainer.tsx, client/src/hooks/useWish.ts
- #250 
0.5h
- 색상 정리
- 서버 에러는 toast.error
- 클라이언트 에러는 toast.info
- 서버 default 에러
- toast.error
- error 페이지로 이동
=> [#250] 토스트 색상 정리

client/src/components/Login/Login.test.tsx, client/src/components/Login/Login.tsx, client/src/containers/LoginContainer.tsx, client/src/stores/userStore.ts
=> [#259] 페이스북 로그인 주석 제거, 테스트 코드 수정

client/src/components/WishList/WishItem/WishItem.tsx
=> [#265] 찜하기 버튼 UX 통일

client/src/components/ConfirmModal/ConfirmModal.tsx, client/src/containers/DeliveryAddressItemContainer.tsx
- #267 
1.5h
- 배송지 삭제 시 confirm 모달로 확인
=> [#267] 배송지 관리에서 삭제 시 confirm 모달

client/src/components/App/App.tsx, client/src/components/Loading/Loading.tsx, client/src/components/ProductList/ProductItem/ProductItemDescription.tsx, client/webpack.common.js, client/webpack.prod.js
- #262
1.0h
- React lazy 로딩을 라우터별로 적용
- node_modules를 캐싱해서 사용할 수 있도록 vendor 설정
=> [#262] 코드 스플리팅 및 웹팩 설정 변경

client/src/components/Cart/Cart.tsx, client/src/index.html
=> [#272] 사용하지 않는 폰트 제거

client/src/components/LazyImage/LazyImage.tsx, server/src/controllers/auth-controller.ts
=> [#274] 콘솔로그 제거, 시연용 아이디 uuid 적용

client/src/components/Cart/Cart.tsx, client/src/components/Cart/CartModal/CountOption/ProductCounter.tsx, client/src/components/Footer/Footer.tsx, client/src/components/Header/HeaderMain/HeaderMain.tsx, client/src/components/Header/HeaderMain/SearchBar/SearchBar.tsx, client/src/components/Header/NavBar/NavBar.tsx, client/src/components/MainProductSections/MainProductList.tsx, client/src/components/ProductDetail/ProductCart/ProductCartItem.tsx, client/src/components/ProductDetail/ProductCart/ProductCounter.tsx, client/src/components/ProductDetail/ProductInfoBox.tsx, client/src/components/ProductList/ProductItem/ProductItem.tsx, client/src/components/Review/ReviewPost/ReviewPostModal/ReviewPostForm/ReviewPostImages/ReviewPostImages.tsx, client/src/index.html, client/src/lib/router.tsx
- #277 
- #254 
0.5h
revert한 브랜치 다시 적용
=> [#277] 웹 접근성 향상 적용

client/src/components/Login/Login.test.tsx, client/src/components/Login/Login.tsx, client/src/containers/LoginContainer.tsx
=> [#279] 페이스북 로그인 주석처리

client/src/components/Review/ReviewList/ReviewListItem/ReviewDetail/ReviewDetailImage/ReviewDetailImage.tsx
=> [#282] 리뷰 디테일 이미지 중복 제거

README.md
- #285
2.5h
팀 기술 및 활동 README 정리
=> [#285] README 정리

client/src/components/App/App.tsx, client/src/components/Loading/Loading.tsx
=> [#288] React lazy Fallback 컴포넌트
